theme: jekyll-theme-minimal

title: [Haoran Zhu]
description: PhD student in Optimization  <br> <br> Email&#58; hzhu94 &#91;at&#93; wisc &#91;dot&#93; edu <br> <a href="https://www.linkedin.com/in/haoran-zhu-967480b9/"> LinkedIn</a>
logo: photo.jpeg
github: is\_project\_page:false


author:
  name             : "Hongyi Wang"
  avatar           : "profile.jpg"
  bio              : "PhD Student at CS of University of Wisconsin - Madison"
  location         : "3533, 1415 Engineering Drive"
  employer         :
  googlescholar    : "https://scholar.google.com/citations?user=zYdZORsAAAAJ&hl=en&citsig=AMstHGSDd6LPeGN0xKe4jqF6gPRY_1K2Pw"
  email            : "hongyiwang@cs.wisc.edu"
