theme: jekyll-theme-minimal
title: [Haoran Zhu]
description: PhD student in Optimization  <br> <br> Email&#58; hzhu94 &#91;at&#93; wisc &#91;dot&#93; edu <br> <a href="https://www.linkedin.com/in/haoran-zhu-967480b9/"> LinkedIn</a> &emsp;<a href="https://drive.google.com/file/d/1Wj9qEdy-6-pKwck_VSDa0HhuOLkiGc7M/view"> CV</a> 
logo: photo.jpeg
github: is\_project\_page:false


