theme: jekyll-theme-minimal
title: Haoran Zhu
description: ML & Optimization Researcher <br> <br> Email&#58; hzhu94 &#91;at&#93; wisc &#91;dot&#93; edu <br> <a href="https://www.linkedin.com/in/haoran-zhu-967480b9/"> &#91;LinkedIn&#93; </a> <a href="https://scholar.google.com/citations?hl=en&user=0JF0e4IAAAAJ"> &nbsp; &#91;Google Scholar&#93; </a> <a href="https://drive.google.com/file/d/1bq6royd9TzeOE_YHh5eLtw49hm0vn20j/view?usp=sharing"> &nbsp;&#91;CV &#93;
logo: photo.jpeg
