theme: jekyll-theme-minimal
title: [Haoran Zhu]
description: PhD student in Optimization  <br> <br> Email&#58; hzhu94 &#91;at&#93; wisc &#91;dot&#93; edu <br> <a href="https://www.linkedin.com/in/haoran-zhu-967480b9/"> &#91;LinkedIn&#93;</a> <a href="https://twitter.com/HaoranZhu5/"> &nbsp; &#91;Twitter&#93;</a>  <a href="https://scholar.google.com/citations?hl=en&user=JF3icl4AAAAJ"> &nbsp; &#91;Google Scholar&#93;</a>  
logo: photo.jpeg
github: is\_project\_page:false
